version: "3"
services:
  auth-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_NAME=auth_microservice
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=localhost
      - JWT_SECRET=this_is_my_jwt_secret
      - PORT=3000
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: auth_microservice
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
